### ISSUE TITLE
[task] Environment preparations

### ISSUE THREAD

**Issue by themetronome** [Atlantis-Academy/react-learn-themetronome#2]
**Подготовка окружения к работе:**

- Необходимо установить Visual Studio Code и некоторый список плагинов для vscode

> Visual Studio Code уже была установлена, и определённый список экстеншенов тоже уже сформирован. По ходу курса по необходимости буду добавлять определённые расширения (напр. сниппеты и тп)

- Установить Node.js на локальную машину

> Node.js тоже была установлена. Немного углубился в тему ноды как окружения, исторические предпосылки для возникновения такой технологии как node.js, какие задачи решает и тд. В ближайшее время планирую вернуться к этой теме и изучить более подробно

- Установить JSHint, разобраться что это такое, и как с ним работать

> Установил JSHint как экстеншн для vscode, и как глобальный пакет через npm(так как он работает на node.js). Прикольный статический анализатор, который может спасти от некоторого ряда ошибок "на лету". Попробовал написать конфиги как локальные так и глобальные, на личных проектиках. Аналоги (JSLint - вроде, устарел, код прогоняется через сайт тулзы что не позволяет анализировать код сразу. Ну и другой аналог CloureCompiler - я не углублялся, просто буду знать что он есть)

**Comment by TorinAsakura** [comment]
@themetronome нихера, на каждое задание - своя задача, иначе как я буду отслеживать твой прогресс? Или ты будешь коммитить от одной задачи все задачи?

**Comment by TorinAsakura** [comment]
@themetronome в качестве закрывающего (и первого) ПРа можешь сделать коммит с конфигом для своей .vscode.
Вообще это хорошая практика хранить конфиги в облаке
